name: Build for Windows 10+ amd64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_windows-2025:
    runs-on: windows-2025
    permissions: write-all

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git python base-devel make unzip zip tar
        pacboy: >-
          toolchain:p
          autotools:p
          cmake:p
          ninja:p
          libusb:p
          wget:p
          boost:p
          fftw:p
          sqlite3:p
          nsis:p

    - name: Setup build directories
      shell: msys2 {0}
      run: |
        mkdir -p js8libs
        mkdir -p build

    - name: Prebuilt Release download for QT6 6.6.3
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'wmiler/js8call'
        fileName: 'qt663-windows-msys2-binaries*.zip'
        tag: 'qt6-v6.6.3-ci'
        extract: true
        out-file-path: 'D:/a/_temp/msys64/mingw64/'

    - name: Prebuilt Release download for Hamlib 4.6.4
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'wmiler/js8call'
        fileName: 'hamlib-windows-msys2-binaries*.zip'
        tag: 'hamlib-v4.6.4-ci'
        extract: true
        out-file-path: 'D:/a/_temp/msys64/mingw64/'
       
# Below is the workaround for installing OmniRig on the Github runners
# which is just everything in Program Files (86)\Afreet directory plus the reg file.
# Would be nice to move the zip and reg to somewhere more public.
    - name: Fetch OmniRig.tar.gz from my site
      run: |
        Invoke-WebRequest -Uri "https://www.spacemonitoring.com/OmniRig120.tar.gz" -OutFile ".\OmniRig120.tar.gz"
        Invoke-WebRequest -Uri "https://www.spacemonitoring.com/OmniRig120.reg" -OutFile ".\OmniRig120.reg"

    - name: Untar/gzip to Program Files (x86)
      run: tar -xzf ".\OmniRig120.tar.gz" -C "C:\"

    - name: Add registry entries so OmniRig cmake works
      run: |
        reg import .\OmniRig120.reg
                
    - name: Configure JS8Call
      shell: msys2 {0}
      run: |
        cd ./build
        cmake -G "MinGW Makefiles" ..

    - name: Build JS8Call
      shell: msys2 {0}
      run: |
        cd ./build
        cmake --build . --config Release --target package

    - name: Upload Artifact (from github runner)
      uses: actions/upload-artifact@v4
      with:
        name: js8call-2.3.2-devel-win64-github.exe
        path: "build/js8call-2.3.2-devel-win64.exe"
